export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const REQUEST_ROBOTS_PENDING = "REQUEST_ROBOTD_PENDING";
export const REQUEST_ROBOTS_SUCCESS = "REQUEST_ROBOTD_SUCCESS";
export const REQUEST_ROBOTS_FAILED = "REQUEST_ROBOTD_FAILED";
